"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import Appbar from "./_components/AppBar/AppBar";

import Cookies from "js-cookie";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log("hello");
  // const jwt = Cookies.get("jwt");
  // console.log("jwt", jwt);
  return (
    <html lang="en">
      <head>{/* <ColorSchemeScript /> */}</head>
      <body>
        <MantineProvider>
          <div
            style={{
              display: "flex",
              flexDirection: "row",
            }}
          >
            <Appbar />
            <div className="children">{children}</div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
